name: Build and test (Release)

on:
  pull_request:
    branches:
      - '**'

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Install tool dependencies
      run: dotnet tool restore
    - name: Build (Debug, for doc scripts)
      run: dotnet build --configuration Debug --no-restore --verbosity normal
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Run fsdocs
      run: dotnet fsdocs build --eval --strict --properties Configuration=Release

  build_windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Install tool dependencies
      run: dotnet tool restore
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal

  build_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Install tool dependencies
      run: dotnet tool restore
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore --verbosity normal
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
